/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ranime.player;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

import LoginRegister.LoginForm;

/**
 *
 * @author Rivaldo
 */
public class HomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        muatKatalogDinamis(); // Tambahkan baris ini!
    }
    
    private void muatKatalogDinamis() {
        // 1. Array data simulasi (Nanti bisa diganti dengan data dari MySQL)
        Anime[] daftarAnime = {
            new Anime("Naruto Shippuden", "", "C:\\Users\\Rivaldo\\OneDrive\\Videos\\Captures\\TestVideo.mp4"),
            new Anime("Spy x Family", "", "C:\\Users\\Rivaldo\\OneDrive\\Videos\\Captures\\TestVideo2.mp4"),
            new Anime("Demon Slayer", "", "C:\\Users\\Rivaldo\\OneDrive\\Videos\\Captures\\TestVideo3.mp4"),
            new Anime("One Piece", "", "C:\\Users\\Rivaldo\\OneDrive\\Videos\\Captures\\TestVideo4.mp4"),
            new Anime("Jujutsu Kaisen", "", "D:/Video/jjk.mp4"),
            new Anime("Kaichou Wa Maid Sama", "", "C:\\Users\\Hype GLK\\OneDrive\\Dokumen\\NetBeansProjects\\Clone\\Ranime\\Kaichou wa maid sama.mp4")
        };

        // 2. Looping untuk mencetak kotak UI satu per satu
        for (Anime anime : daftarAnime) {
            
            // a. Buat Kotak Pembungkus
            JPanel panelItem = new JPanel();
            panelItem.setLayout(new BorderLayout()); 
            panelItem.setPreferredSize(new Dimension(295, 215)); // Ukuran yang sudah kita hitung tadi
            panelItem.setBackground(new Color(100, 100, 255)); // Warna ungu kebiruan sementara

            // b. Buat Tombol Thumbnail (Bisa diklik)
            JButton btnThumb = new JButton();
            btnThumb.setContentAreaFilled(false); // Hilangkan background tombol
            btnThumb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            
            // Event klik: Nanti ini akan memutar video
            // Cari bagian ini di dalam method muatKatalogDinamis() pada HomePage.java
            btnThumb.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    // 1. Cetak ke console untuk monitoring (opsional)
                    System.out.println("Membuka pemutar untuk: " + anime.getJudul());
                    
                    // 2. JALANKAN WINDOW PEMUTARNYA DI SINI:
                    // Membuat objek PlayPage baru sambil mengirimkan path video anime yang diklik
                    PlayPage pemutar = new PlayPage(anime.getVideoPath());
                    
                    // Memunculkan window pemutar ke layar
                    pemutar.setVisible(true); 
                }
            });

            // c. Buat Teks Judul
            JLabel lblJudul = new JLabel(anime.getJudul(), SwingConstants.CENTER);
            lblJudul.setForeground(Color.WHITE);

            // d. Susun tombol dan judul ke dalam Kotak
            panelItem.add(btnThumb, BorderLayout.CENTER);
            panelItem.add(lblJudul, BorderLayout.SOUTH);

            // e. Masukkan Kotak ke dalam wadah utama (panelKatalog)
            panelKatalog.add(panelItem);
        }

        // 3. Beritahu UI untuk memperbarui tampilan
        panelKatalog.revalidate();
        panelKatalog.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnbookmark = new javax.swing.JLabel();
        btnhistory = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelKatalog = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Logo");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");

        btnbookmark.setForeground(new java.awt.Color(255, 255, 255));
        btnbookmark.setText("Bookmarks");
        btnbookmark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbookmarkMouseClicked(evt);
            }
        });

        btnhistory.setForeground(new java.awt.Color(255, 255, 255));
        btnhistory.setText("Watched");
        btnhistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhistoryMouseClicked(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(btnbookmark)
                .addGap(64, 64, 64)
                .addComponent(btnhistory)
                .addGap(441, 441, 441)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnbookmark)
                    .addComponent(btnhistory)
                    .addComponent(btnLogout))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBar(null);

        panelKatalog.setBackground(new java.awt.Color(255, 255, 204));
        panelKatalog.setPreferredSize(new java.awt.Dimension(1320, 700));
        panelKatalog.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 28, 28));
        jScrollPane1.setViewportView(panelKatalog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1338, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
         int pilihan = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin logout?", 
                "Konfirmasi Logout", 
                JOptionPane.YES_NO_OPTION);

        if(pilihan == JOptionPane.YES_OPTION){
            this.dispose();
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnhistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhistoryMouseClicked
        // TODO add your handling code here:
        this.dispose(); // tutup register                           
        new Watched().setVisible(true); // buka form watched
    }//GEN-LAST:event_btnhistoryMouseClicked

    private void btnbookmarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbookmarkMouseClicked
        // TODO add your handling code here:
        this.dispose(); // tutup register                           
        new Bookmarks().setVisible(true); // buka form login
    }//GEN-LAST:event_btnbookmarkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel btnbookmark;
    private javax.swing.JLabel btnhistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelKatalog;
    // End of variables declaration//GEN-END:variables
}
